server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/platform_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/platform-demo}

management:
  endpoints:
    web:
      exposure:
        include: health
