server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: platform-api
          uri: ${PLATFORM_API_URI:http://localhost:8081}
          predicates:
            - Path=/api/platform/**
        - id: business-a
          uri: ${BUSINESS_A_URI:http://localhost:8082}
          predicates:
            - Path=/business-a/**
          filters:
            - RewritePath=/business-a/?(?<segment>.*), /${segment}
        - id: business-b
          uri: ${BUSINESS_B_URI:http://localhost:8083}
          predicates:
            - Path=/business-b/**
          filters:
            - RewritePath=/business-b/?(?<segment>.*), /${segment}
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health
